version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document-search
    ports:
      - "8501:8501"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    volumes:
      - .:/app
      - ./files:/app/files
