services:
  - type: web
    name: document-search
    env: python
    buildCommand: |
      pip install poetry
      poetry install --no-root
    startCommand: streamlit run main.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_HOST
        value: qdrant
      - key: QDRANT_PORT
        value: 6333
    plan: free
    autoDeploy: true

  - type: pserv
    name: qdrant
    env: docker
    image: qdrant/qdrant:v1.9.1
    plan: free
    autoDeploy: true
